services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: xx-proxy
    ports:
      - "8080:80"
    networks:
      - dweb-network
networks:
  dweb-network:
    driver: bridge
