name: EC2 Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "myapp/.git" ]; then
              git clone https://github.com/minseokchae1/myapp.git
            fi
            cd myapp
            git pull origin main

            # Node.js 설치
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # 프론트엔드 빌드
            cd frontend
            npm install
            npm run build
            cd ..

            # 빌드용 폴더 복사
            rm -rf proxy/dist
            cp -r frontend/dist proxy/dist

            docker-compose down || true
            docker-compose up -d --build
