name: EC2 Docker Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow files
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_SSH_PORT }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            # myapp 디렉터리가 없으면 HTTPS+토큰으로 클론
            if [ ! -d "myapp" ]; then
              git clone https://x-access-token:${GITHUB_TOKEN}@github.com/minseokchae1/myapp.git myapp
            fi
            cd myapp
            git pull origin main

            # Docker 컨테이너 재시작
            docker-compose down || true
            docker-compose up -d --build
