name: EC2 Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_SSH_PORT }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          key_encoding: base64
          script: |
            cd ~/myapp
            git pull origin main
            docker-compose down
            docker-compose up -d --build
